### ISSUE TITLE
"[download] Limit reached for max number of failed attempts`"

### ISSUE THREAD

**Issue by molakirlee** [osmoscraft/osmosfeed#71] opened 2021-07-22 13:59 UTC
Hi, 

I met a problem "[download] Limit reached for max number of failed attempts`" sometimes. I think it is because the RSS source is not stable enough. Is there any way to increase the max number of attempts? Or any other method to deal with this error?

Thank you very much,
Xilock

```
[get-cache] Use remote cache: https://molakirlee.github.io/feed/cache.json
[discover-cache] Pre-build cache restored: https://molakirlee.github.io/feed/cache.json
[enrich] 0.16s |  30 cached |   0 new | https://rsshub.app/geekpark/breakingnews
[enrich] 3.85s |  36 cached |   1 new | https://sspai.com/feed
[download] 2 attempts left, error download https://rsshub.app/wallstreetcn/news/global ECONNABORTED
[download] 2 attempts left, error download https://rsshub.app/bbc/world-asia ECONNABORTED
[download] 2 attempts left, error download https://rsshub.app/wallstreetcn/live ECONNABORTED
[download] 1 attempts left, error download https://rsshub.app/wallstreetcn/news/global ECONNABORTED
[download] 1 attempts left, error download https://rsshub.app/bbc/world-asia ECONNABORTED
[download] 1 attempts left, error download https://rsshub.app/wallstreetcn/live ECONNABORTED
[download] 0 attempts left, error download https://rsshub.app/wallstreetcn/news/global ECONNABORTED
/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31614
      throw new Error(`[download] Limit reached for max number of failed attempts`);
            ^

Error: [download] Limit reached for max number of failed attempts
    at downloadHelper (/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31614:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async enrichInternal (/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31664:21)
    at async Promise.all (index 2)
    at async run (/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31875:27)
Error: Process completed with exit code 1.
```

**Comment by chuanqisun** [comment] 2022-01-10 05:19
Hi @molakirlee and @philippnagel, I've moved your issue from the template repo to the main repo. I'm sorry I didn't see this earlier. I don't track the issues in the template repo as often.

This is a duplicate of #67, I have fixed it with PR #72 and is released for v1.13.0

Note that some network errors are impossible to recover, no matter how many retires we have. So the latest logic will just fallback to the cached content, instead of crashing the build.

Let me know if it works as expected. Thank you again for helping out.

**Closed by chuanqisun** 2022-01-10 05:19 UTC
